services:
  gateway:
    build: .
    container_name: gateway
    environment:
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - reactive-ms-network

networks:
  reactive-ms-network:
    external: true
